version: 0.0
os: linux
files:
  - source: /
    destination: /application
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 800
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 800
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 800
      runas: root
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 800
      runas: root
