global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 6s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 24.199.122.125:6541
          - 24.199.122.125:6542
          - 24.199.122.125:6543
#  - job_name: dropwizard
#    metrics_path: /metrics
#    scrape_interval: 5s
#    scheme: http
#    static_configs:
#      - targets:
#          -localhost:8081